// REPLY ALL — Game Content

export const PREMISES = [

  // ——— OFFICE ———
  "The office has introduced a formal sign-out sheet for the good stapler. You were not consulted on the design of the sheet.",
  "Someone has eaten the clearly labeled birthday cake in the fridge two days before the birthday.",
  "A coworker has begun ending all emails with 'Per my last email' regardless of whether they have sent a previous email.",
  "The conference room has been double-booked for the third consecutive Thursday by someone who does not appear to work in this building.",
  "HR has asked everyone to complete a mandatory 'Desk Personalization Appropriateness' self-assessment by end of quarter.",
  "A colleague has CC'd the entire department on a reply that says only 'Thanks!'",
  "The printer has been out of paper for eleven days. There is a full ream of paper on top of the printer.",
  "Someone in the open-plan office is eating soup every day at 11:42 AM and has not acknowledged any of the ambient sighs.",
  "The team has been asked to fill out a survey to determine whether they need more meetings.",
  "The new performance review system rates employees on a scale from 'Developing' to 'Exceptional.' Your rating is 'Developing.' You built the system.",
  "HR has notified you that your sick day last Tuesday has been flagged because it was adjacent to a public holiday, which is 'a known pattern.'",
  "The new office manager has rearranged the kitchen cabinets and sent an email explaining the new system. The system is worse.",
  "Someone has put a passive-aggressive note on the shared fridge that reads 'LABELLED ITEMS = OFF LIMITS.' Their item is not labeled.",
  "A colleague has taped over your name on your cubicle and replaced it with a motivational quote. The quote is attributed to them.",
  "The company's AI tools mandate requires everyone to use the chatbot before emailing IT. The chatbot is named Gerald. Gerald does not work. You have told Gerald about the printer issue fourteen times.",
  "The office has installed a 'vibe check' whiteboard near the entrance where employees mark their current energy. Facilities has emailed asking why you draw a skull every day.",
  "Your calendar has been shared with the team 'for visibility.' You had a block labeled 'personal' on Tuesday. There are six questions about it in Slack.",
  "The end-of-year party committee has requested dietary restrictions for an event with a menu that is entirely bread.",
  "The company has introduced a mandatory fun initiative. Participation in mandatory fun is voluntary. Non-participation has been noted.",
  "A meeting scheduled as 30 minutes has been running for 90. The person speaking has just said 'So, to circle back to slide one.'",
  "Your access to the stationery cupboard has been revoked pending a review of last quarter's Post-it note usage.",
  "Someone has added a 'Fun Zone' to the office. It is a beanbag chair next to the fire exit. Use of the Fun Zone requires a booking.",
  "The building's hot desking policy means you have arrived to find someone at your desk. They have personalized it. There is a succulent and a framed photo of their family.",
  "The new 'open feedback' initiative has produced one piece of feedback, submitted anonymously, which describes you as 'a lot.'",
  "The wellness committee has added a 'Gratitude Wall' in the break room. Someone has posted 'I am grateful for the stapler.' It is your handwriting. You did not write it.",

  // ——— CUSTOMER SERVICE / BUREAUCRACY ———
  "A form you submitted has been returned because it was completed in black ink rather than blue ink. The form did not specify.",
  "Your warranty claim has been declined on the grounds that the product was used 'in an environment consistent with normal use.'",
  "The automated helpline has transferred you to a department that transfers you back to the automated helpline. You have completed this loop four times.",
  "A subscription you cancelled has been renewed under a new name that is legally distinct from the original subscription.",
  "Your refund request has been approved, pending a refund of the original refund you received for the refund that was incorrectly processed.",
  "The council has sent a letter asking you to confirm your address so they can update their records with your new address, which is your old address.",
  "Your complaint has been escalated to a specialist team who escalated it back to the original team with a note that says only 'see original complaint.'",
  "You have been placed on hold for 47 minutes and the estimated wait time is still three minutes.",
  "The bank has flagged a suspicious transaction. The suspicious transaction is your rent, which you have paid from the same account, on the same day, for four years.",
  "Your parcel has been marked 'delivered' and photographed on a doorstep. That is not your doorstep. You do not recognize that doorstep. No one on your street recognizes that doorstep.",
  "A customer service agent has closed your ticket with the resolution 'User educated.' You were not educated. You were told to try turning it off and on again and then disconnected.",
  "You have been issued a parking fine for a car you do not own, in a city you have never visited, on a date your passport confirms you were in a different country. The fine is for 'attitude.'",
  "You have received a satisfaction survey about an experience you have not yet had. The survey closes before the experience begins.",
  "The website says to call. The phone says to visit the website. You have done this seventeen times. You are beginning to understand you are part of a study.",
  "You have received a letter informing you of a data breach. The letter contains your data.",

  // ——— NEIGHBOURS / SUBURBIA ———
  "Your neighbor has left a passive-aggressive note about which bin day it is, with the days underlined twice.",
  "The HOA has flagged your garden gnome as 'non-compliant' and cited it under Section 4(b) of the Aesthetic Harmony Guidelines.",
  "Your neighbor has installed a second motion-sensor light that illuminates your bedroom window specifically.",
  "Your neighbor has begun mowing at 7:58 AM on Saturdays, which is technically two minutes before the noise ordinance begins.",
  "A note under your door informs you that your wind chime constitutes an 'ongoing auditory trespass.'",
  "A handwritten note requests that you 'consider the visual impact' of your holiday lights, which you have not yet put up.",
  "Your neighbor has taken to placing their recycling bin precisely two inches over your property line and has denied this when asked.",
  "The street has convened an informal parking committee. You were not invited but your car is on the agenda.",
  "A neighbor has complained to the HOA that your dog 'stares.' The HOA has opened a formal inquiry into the staring.",
  "The neighborhood Facebook group has been used to share a photo of 'suspicious activity.' The photo is of you, walking your dog, at a normal time, with a normal expression.",
  "Your neighbor has begun composting. This is fine. However, they have written you a letter detailing everything they are composting and it reads like a confession.",
  "The HOA newsletter has included a diagram of your yard with proposed 'improvements' the committee would like to see. One of the improvements is that you move.",
  "A note on your door reads 'Please see me at your earliest convenience.' It is not signed. No neighbor has acknowledged leaving it. A second note appeared this morning. It says 'Well?'",
  "Your neighbor has reported you to the city for 'aggressive landscaping.' Your lawn is a normal lawn. It has always been a normal lawn. The complaint includes a timeline.",
  "Someone on your street has submitted a petition. The petition has one demand. The demand is that you close your blinds earlier. It has twelve signatures. One signature is your mother's.",

  // ——— FAMILY GROUP CHATS ———
  "Someone has added you to a new family group chat called 'IMPORTANT' and the first message is a forwarded image about water and lemons.",
  "An aunt has replied 'Seen' to a message in the family group chat that was a birth announcement.",
  "A relative has sent a voice message in the family group chat that is four minutes and thirty seconds long and begins with 'So, I was thinking—'",
  "The family group chat has eleven members. You cannot identify two of them. One of the unidentified members has strong opinions about Easter. The other one just types 'ok' to everything including the birth announcement.",
  "Your grandmother has discovered the 'forward' button and has sent the same sunset image eleven times this week. When asked, she says she 'wanted to make sure everyone saw it.' She is now sending it to confirm you saw it.",
  "A family member has used the group chat to relitigate a disagreement from 2014. They have receipts. The receipts are a printed email chain. The email chain was printed for this specific moment.",
  "A relative has texted the family group chat asking everyone to call them urgently. When called, they want to know if you've tried a particular brand of yogurt.",
  "Your cousin has forwarded a chain message requiring you to send it to ten people within ten minutes 'or something bad will happen.' Two relatives have already complied. Your uncle has sent it forty times to be safe.",
  "A family member has begun narrating their daily routine in the group chat as dramatic life updates. Today's installment: 'Had toast. Brown bread. They were out of white. I don't want to talk about it.' There are six replies asking if they're okay.",
  "Someone in the family group chat has replied 'Who is this?' to a message sent by the person who created the group.",
  "The family holiday location poll has concluded. Second place, by one vote, was staying home. The location chosen is not accessible by public transport. It has no Wi-Fi. The person who chose it does not have a car.",
  "A family member has added their ex to the group chat 'by accident' and then gone offline. The ex has sent a thumbs up to seven messages.",

  // ——— SCHOOL / PARENTS ———
  "The PTA bake sale requires items to be 'store-bought for safety reasons' and also 'homemade to reflect community spirit.' The contradiction has been raised. The PTA has said both still apply.",
  "Your child has told their teacher something you said at home. The teacher has emailed to discuss it. The email is very measured. There is a follow-up scheduled.",
  "The school newsletter has confirmed that the science fair project your child submitted, which you spent forty hours on, has been disqualified for being 'too polished.'",
  "A permission slip for a field trip to a local park requires a signature, a medical disclaimer, emergency contacts, proof of insurance, and a paragraph about your child's 'learning goals for the experience.'",
  "The class WhatsApp group has 34 parents in it. A message has gone out about a bake sale. Thirty-one parents have sent a thumbs up. Two have sent paragraphs. One has called an emergency.",
  "Your child has been selected for a speaking role in the school play. The role is 'Narrator.' They have no lines. They stand at the side. The program describes the narrator as 'essential.'",

  // ——— SMALL BUSINESS / FREELANCE ———
  "A client has approved a final design, received the files, and is now requesting 'minor adjustments' eleven months later.",
  "A competitor has opened directly across the street and named their business your business name with 'and More' appended.",
  "A client has asked you to lower your rate because 'AI can do this now.' The client does not use AI. The client has a fax machine. The client has two fax machines.",
  "A supplier has invoiced you for a service not rendered, cited a contract clause that does not exist, and marked the email 'URGENT: THIRD NOTICE.'",
  "A client who owes you money has just posted a photo of their new boat on Instagram, captioned 'Finally!' The boat is named after your invoice.",
  "A customer has returned a product with the note 'not what I expected.' They have not described what they expected. A follow-up note clarifies only that it was 'more.'",
  "A five-star review has been removed by the platform as 'potentially incentivized' because the customer wrote that they 'genuinely liked it here.' The platform has also removed two of your other five-star reviews as 'emotionally suspicious.'",
  "A client has emailed asking 'Is this you?' with a screenshot of a Yelp review you definitely did not write, but which does sound like you, and which ends with a threat.",

  // ——— TECHNOLOGY / INTERNET ———
  "A Facebook friend you met once at a conference in 2011 has liked a photo from your 2014 vacation, a photo from 2009, and your profile picture from 2017. In that order. At 2 AM. Then unliked them all.",
  "An app has sent you a notification that says 'We miss you! 😢' You have been using the app every day for three years.",
  "Someone has added you to a group text with people you don't know and the first message is 'hey everyone, almost there!' The location is not specified. Fourteen people have replied 'us too!' You have replied asking where. No one has answered.",
  "A reply-all chain has started at a company you no longer work for. You are still on the distribution list. Seventeen people have replied asking to be removed. Each removal request triggered another reply-all. You are now the most-replied-to person in the chain for having said nothing.",
  "A LinkedIn influencer you do not follow has sent you a connection request with the message 'I don't connect with everyone — but something told me to reach out.' They have attached a PDF. The PDF is about them.",
  "Your streaming service has introduced a feature that asks you to confirm you are still watching. You are still watching. You have always been watching. The feature now asks every four minutes. You feel it is asking about more than the show.",
  "The company's AI customer service bot has replied to your complaint with a message that addresses none of your complaint. It ends: 'We're so glad we could help! 🌟' You were not helped.",
  "You have received an email with the subject line 'Did you forget something?' You did not forget something. It is a cart abandonment email for a single zip tie.",

  // ——— FULLY UNHINGED ———
  "You have received a certified letter informing you that you have been nominated for an award you did not apply for. The award is for the person who has caused the most inconvenience to a specific individual this calendar year. There is a gala. You are expected to give a speech.",
  "A formal complaint has been lodged against you by a pigeon. The complaint has been forwarded in writing by a local wildlife advocacy group. It is twelve pages. The pigeon has a lawyer.",
  "You have received an invoice for emotional labor from someone with whom you had a minor disagreement last spring. There is a late fee. The invoice has been sent to collections.",
  "The gym has contacted you because a personal trainer has filed a grievance about the way you use the elliptical. He says you 'do it wrong.' There are diagrams. The diagrams have been laminated.",
  "You have received a cease and desist letter regarding a wave you gave to someone on the street. The letter argues the wave was 'aggressive in nature, intent, and wrist articulation.'",
  "The restaurant has emailed after your visit. They would like to discuss the way you sent back the bread. There was nothing wrong with the bread. That is the issue.",
  "You have been removed from a neighborhood book club for 'not engaging authentically with the text.' The text was a menu.",
  "The barista at your regular coffee shop has submitted a formal complaint about the way you say 'thank you.' It is, per the complaint, 'too sincere, and escalating.'",
  "You have received an invitation to join a 'waitlist' for a 'premium version' of a park you have been going to for free your entire life. The waitlist is two years. There is an application fee.",
  "A council notice has been taped to your door formally requesting that you stop looking 'a little smug' when you put your bins out correctly, as it is 'demoralizing to the street.' The notice is co-signed by four neighbors.",
  "You have received a formal objection to a sigh you emitted in a public place last Thursday. The objection notes the sigh was 'audible, prolonged, and editorializing.' It requests a written account of what the sigh was about.",
  "You have been issued a verbal warning, in writing, for laughing at something in a meeting that was not, according to the meeting minutes, supposed to be funny. The meeting minutes also note that your expression 'remained amused' for several minutes afterward.",
  "A local artisan has filed a trademark dispute over a phrase you use to describe your weekend. The phrase is 'fine, I guess.' They have been using it since 2019. There is a paper trail.",
  "The library has sent a notice. You have had 'Catch-22' checked out for three years. They do not want it back. They want to know if you are okay. A librarian will be calling.",
  "You have received a bill from a stranger for 'ambient consulting' you provided by thinking loudly on public transport during their commute. The rate is $85/hr. The bill is itemized. Item 7 is 'sighing about the economy.'",
  "Someone has filed a missing persons report on your personality. HR has forwarded it to you with the note 'for your awareness.' There is a description. The description is accurate.",
  "Your dentist has emailed to let you know that based on your X-rays, they can tell what kind of year you're having, and they'd like to schedule a follow-up that isn't about your teeth.",
  "You have received a formal complaint from your upstairs neighbor about the sound of you lying very still at 3 AM. They describe it as 'deliberate' and 'escalating.' They have included a sound recording. It is silence.",
  "A meditation app has sent you a cease and desist letter. You have been using a competitor app. The letter is written in a very calm font. It is the most threatening thing you have ever read. There is a section on 'mindful legal action.'",
  "An independent auditor has reviewed your grocery receipts and produced a twelve-page report on what they reveal about your 'decision-making framework as a person.' The executive summary is a single word: 'concerning.'",
  "You have been selected to participate in a community mural. Your face will be included. You will be in the background. You will be depicted as small. There is no opt-out. The artist says it is 'important that you're in there.'",
  "Your therapist has forwarded your session notes to HR by accident. The notes contain the sentence 'client is coping.' HR would like to schedule a meeting to discuss what you are coping with.",
  "A stranger has sent you a LinkedIn message thanking you for the 'energy you brought to the elevator' last Tuesday. They would like to formally collaborate. They have attached a deck. The deck is about the elevator.",
  "You have received a letter from your bank noting that your savings account activity suggests you may be 'quietly spiraling' and they would like to offer you a product.",
  "The fire drill was last Thursday. You were the last one out. The building had been empty for forty minutes. An official report has been filed. It describes your expression as 'unbothered, which was its own kind of concern.'",
  "An automated wellness check from your employer has flagged that you have not used any exclamation points in your emails this month. HR would like to know if everything is okay. The email asking if everything is okay does not contain any exclamation points.",
  "You have received a formal notice that a documentary is being made about your street. You are not the focus of the documentary. You are described in the treatment as 'a recurring presence whose role will become clear.'",
  "A neighbor has filed a complaint with the city about the way your house 'sits.' Not what you've done to it. The way it sits. The complaint includes the phrase 'architecturally passive-aggressive.'",
  "The person behind you in the coffee shop line has submitted a written account of your order to Yelp. The review is of you. It is three stars. The complaint is that you 'took a moment' before ordering.",
  "You have received a court summons. It is for small claims court. The claim is $4. The plaintiff has attached 200 pages of supporting documentation. Page 47 is a photo of you from a distance, circled in red.",
  "Your landlord has sent a formal notice that your apartment has been entered 'for a routine inspection.' Nothing was moved. Nothing was taken. But something has been rearranged in a way that proves someone was there, and they wanted you to know.",
  "A wildlife charity has sent you a certificate of adoption for an animal you did not adopt. The animal is a vulture. The certificate says it has been named after you. There is a photo. The vulture looks like you.",
];

export const CONSTRAINTS = [
  // — PROCEDURAL —
  "Cite a specific company policy that does not exist. Include a plausible policy number.",
  "CC someone who has nothing to do with this dispute and do not explain why.",
  "Reference an attachment you do not describe or include.",
  "Demand everything be confirmed in writing, including this email.",
  "Quote a regulation or statute number. It does not need to be real.",
  "Begin by noting that you have reviewed previous correspondence 'at some length.'",
  "Propose a formal meeting. Specify that minutes will be taken. Specify who will take them.",
  "Mention that you have already raised this through 'the appropriate channels.'",
  "Include a formal timeline of events starting with an event that is not obviously related.",
  "Mention that legal advice has been sought, without specifying further.",
  "Include a bullet-pointed list of required actions with deadlines. The deadlines must be unreasonable.",
  "Open with 'As per our conversation,' even though no such conversation has taken place.",
  "Invent a committee and suggest it be convened. Give it a name.",
  "State that you are documenting all correspondence. List this email as Exhibit A.",
  "Sign off with a title you have given yourself that is not your actual title.",
  "Close by describing in detail what further escalation would look like.",
  "Refer to the other party by a full name and a title they may not hold throughout.",

  // — TONE & PERSONA —
  "Refer to yourself exclusively in the third person throughout.",
  "State that you are a 'reasonable person' at least twice.",
  "Maintain the energy of someone who has already won and is simply completing the paperwork.",
  "Write as though you have already forgiven the other party but want them to know you have forgiven them.",
  "Adopt the tone of a disappointed but patient parent. You are not their parent.",
  "Write the entire email as if you are very, very calm. Specify at least once that you are very, very calm.",
  "Begin with a compliment so specific and strange it cannot be interpreted as genuine.",
  "Include exactly one sentence of genuine vulnerability, immediately retracted.",
  "Use the phrase 'I think we both know' regarding something only you could possibly know.",
  "Refer to this situation as a 'growth opportunity,' without elaborating.",
  "Express sympathy for the other party in a way that makes things significantly worse.",
  "Never use the word 'problem.' Use increasingly elaborate synonyms. By the end, use at least three different ones.",
  "Write as though you are being filmed for a documentary and are very aware of your legacy.",
  "At no point acknowledge that anything is wrong. Simply describe the situation as 'evolving.'",
  "Refer to your response as 'measured' in the opening line.",
  "Write as though every sentence might one day be read at a trial, and you are fine with that.",

  // — STRUCTURAL CHAOS —
  "Include a P.S. that is longer than the email itself.",
  "Begin with a one-sentence paragraph that is a complete non-sequitur, never referenced again.",
  "Somewhere in the email, include a single bullet point containing the most devastating thing you say. Do not draw attention to it.",
  "Use a footnote. The footnote must raise more questions than it answers.",
  "Your closing salutation must be something you invented. It should feel almost professional.",
  "Include a 'Section 2' even though there was no Section 1.",
  "Format one sentence as a centered pull quote as though it will one day be printed somewhere important.",
  "Begin with an executive summary. The summary must be longer than what follows.",
  "End the email mid-senten",
  "Include a disclaimer at the bottom that fundamentally contradicts the email above it.",
  "Write the first paragraph. Then write it again, slightly differently, as though you think no one will notice.",
  "Add a subject line change mid-email. Do not acknowledge it.",
  "Every paragraph must end with a sentence that makes the previous sentences worse in retrospect.",

  // — WEIRD ESCALATION —
  "Introduce a witness. Do not name them. Do not quote them. Simply confirm that they exist and that they remember.",
  "Mention that you have taken photographs. Do not describe what was photographed.",
  "Hint that there is a document you could share but have chosen not to at this time.",
  "State that you would prefer to handle this quietly but the timeline for quiet handling has elapsed.",
  "Note that you have been advised not to say more on this point. Say slightly more on this point.",
  "Imply that you have already spoken to a journalist, without confirming or denying.",
  "Mention 'the incident at the offsite' without further context.",
  "Treat the matter as already resolved in your favor and simply await paperwork confirmation.",
  "Reference a prior relationship with a senior person without naming them, in a way that implies you could name them.",
  "State that you are prepared to be 'completely transparent,' then be only somewhat transparent.",
  "Close by saying you look forward to a positive resolution 'for everyone's sake' in a way that does not suggest this.",
  "Imply that this situation has happened before, with you, or near you, or around the general time of you.",

  // — PERSONAL CHAOS —
  "Mention that you have not been sleeping well, once, then immediately move on as if you did not say that.",
  "Include a sentence about how you 'didn't want it to come to this.' Do not explain what 'this' is.",
  "Mention your vacation at least once. Make it sound like a threat.",
  "Drop in the phrase 'as I've said many times before' even though you have never said this before.",
  "Reveal in passing that you have been maintaining a log of relevant events 'since at least March.'",
  "Include the phrase 'and frankly' before the least frankly stated sentence in the email.",
  "Mention that you have discussed this with your partner, who also has thoughts.",
  "Reference a personal sacrifice you have made in connection with this situation. Do not specify what it was.",
  "Note somewhere that you 'almost didn't send this email.' You are sending this email.",
  "End with 'I hope this finds you well,' after an email in which you have clearly hoped for the opposite.",
  "Mention, in passing, that you have been keeping a folder. Just a folder. You don't say what's in it.",
  "Somewhere in the email, briefly note that you have already talked to God about this.",
];

// MEGA CONSTRAINTS: ~15% chance, totally unhinged
export const MEGA_CONSTRAINTS = [
  "🔥 MEGA: Write the entire email as a series of rhetorical questions. Every. Single. Sentence.",
  "🔥 MEGA: This email is also a formal eulogy for the professional relationship. Treat it accordingly.",
  "🔥 MEGA: You have retained a child as your legal representative. Refer to their counsel throughout.",
  "🔥 MEGA: This email is a press release. Format it as one. Include a quote from yourself.",
  "🔥 MEGA: You are writing from the future, where this matter has already been resolved badly. You are trying to prevent it.",
  "🔥 MEGA: Include a terms and conditions section at the bottom governing the reading of this email.",
  "🔥 MEGA: This email is also your formal resignation from something. You determine what.",
  "🔥 MEGA: You have formed a union specifically to address this issue. Introduce the union. Give it a name and a motto.",
  "🔥 MEGA: Structure this as a haiku sequence. Three haikus. Each one more litigious than the last.",
  "🔥 MEGA: Introduce an alias you will now be conducting all correspondence under. The alias must be slightly more impressive than your actual name.",
  "🔥 MEGA: Write this as a Yelp review of the person you are replying to. One to five stars. Justify your rating.",
  "🔥 MEGA: Include a satisfaction guarantee for your email. If they are not fully satisfied, they may return it within 30 days for a full emotional refund.",
  "🔥 MEGA: This is also a letter of recommendation for yourself, embedded in the email. It becomes apparent gradually.",
  "🔥 MEGA: Announce a boycott of one oddly specific thing related to the other party.",
  "🔥 MEGA: Write this email as a children's book. It must have a moral. The moral must be upsetting.",
  "🔥 MEGA: Format this as a Wikipedia article about the incident. Include a 'Controversy' section and a 'Legacy' section.",
  "🔥 MEGA: This email is a performance review of the other party. Use a rubric. Score them. Include an 'areas for improvement' section.",
  "🔥 MEGA: Write this as a recipe. The dish represents the situation. Include prep time, cook time, and a difficulty rating.",
  "🔥 MEGA: End every sentence with an academic citation. The sources do not need to exist.",
  "🔥 MEGA: Write this as the terms of a peace treaty. Both parties must be referred to by the names of small landlocked countries.",
  "🔥 MEGA: Format the email as a job listing for the role of 'person who handles this situation correctly.' Include salary range and a note that the position has been open for some time.",
  "🔥 MEGA: This email is a voicemail transcription from someone who did not realize they had reached voicemail and kept going anyway.",
  "🔥 MEGA: Respond entirely in the form of FAQs — written by you, answered by you, about this situation.",
  "🔥 MEGA: This email must include a glossary at the end redefining words you used normally with new, very specific meanings.",
  "🔥 MEGA: Write this as a hotel review. The hotel is the relationship. The minibar has been a disappointment.",
  "🔥 MEGA: Present this as meeting minutes from a meeting that did not take place. You were the chair. There was a quorum. One attendee is listed as 'The Situation Itself.'",
  "🔥 MEGA: This is also an RSVP. To something. The event details are vague but the dress code is formal.",
  "🔥 MEGA: Write this as a nature documentary narration. You are the larger animal. The other party is described with sympathy.",
  "🔥 MEGA: This email must contain a timeline, a pie chart described in words, and a section titled 'What We Have Learned.'",
  "🔥 MEGA: Write this email as if it is exhibit B. Do not explain what exhibit A was.",
  "🔥 MEGA: This email is a ransom note for something that has not been taken yet. It is a preemptive ransom note. The demand is reasonable.",
  "🔥 MEGA: Write this as a prophecy. It has already come true. You are notifying them of this.",
  "🔥 MEGA: This email is also your will. Specifically the section about this person.",
  "🔥 MEGA: Write this as a wine tasting note. The wine is this entire situation. Finish is long and accusatory.",
  "🔥 MEGA: This email must be written as if it is being translated from a language that does not have a word for what happened, and the translator keeps having to explain it in brackets.",
  "🔥 MEGA: This is a grant application for funding to continue dealing with this situation. Include your methodology and expected outcomes.",
];

export function getRandomPremise() {
  return PREMISES[Math.floor(Math.random() * PREMISES.length)];
}

export function getRandomConstraint() {
  if (Math.random() < 0.15) {
    return MEGA_CONSTRAINTS[Math.floor(Math.random() * MEGA_CONSTRAINTS.length)];
  }
  return CONSTRAINTS[Math.floor(Math.random() * CONSTRAINTS.length)];
}
